version: "3.7"
services:
  graphql-service:
    image: node:11-alpine
    hostname: graphql-service
    container_name: graphql-service
    ports:
      - "4000:4000"
    volumes:
      - "./:/src"
    command: [ "node", "/src/index.js" ]
